- hosts: servers
  become: yes
  vars:
    ip_modules:
      - ip_vs
      - ip_vs_rr
      - ip_vs_wrr
      - ip_vs_sh
      - br_netfilter  

  tasks:
   - name: disable firewall 
     service:
        name: firewalld
        state: stopped
        enabled: false

   - name: Disable SWAP 
     shell: |
       swapoff -a

   - name: Disable SWAP in fstab 
     lineinfile:
       path: /etc/fstab
       regexp: 'swap'
       state: absent

   - name: install yum-utils
     yum: 
      name: yum-utils
      state: present

   - name: install docker repo
     shell: >
      yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

   - name: install docker 
     shell: >
      yum install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin 

   - name: disable SELinux
     command: setenforce 0
     ignore_errors: yes

   - name: disable SELinux on reboot
     selinux:
       state: disabled

   - name: configure network settings
     tags:
      - os-settings
     command: modprobe '{{ item }}'
     loop: '{{ ip_modules }}'

   - name: Modprobe
     tags:
      - os-settings
     lineinfile:
      path: "/etc/modules"
      line: "{{ item }}"
      create: yes
      state: present
     loop: "{{ ip_modules }}"

   - name:  set iptables
     tags:  
      - os-settings   
     sysctl:
      name: '{{ item }}'
      value: 1
      sysctl_set: yes
      state: present
      reload: yes
     loop:
      - net.bridge.bridge-nf-call-ip6tables
      - net.bridge.bridge-nf-call-iptables 

   - name: configure kubernetes repo
     yum_repository:
      name: kubernetes
      description: kubernetes repo
      enabled: 1
      gpgcheck: 1
      ip_resolve: whatever
      keepalive: yes
      baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
      gpgkey: 
        - https://packages.cloud.google.com/yum/doc/yum-key.gpg 
        - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      exclude: 
        - kubelet 
        - kubeadm 
        - kubectl

   - name: install packages
     yum:
      name: '{{ item }}'
      state: latest
      update_cache: true
     loop:
      - kubeadm
      - kubelet
      - kubectl

   - name: start services
     service:
       name: '{{ item }}'
       enabled: true
       state: started
     loop:
      - docker
      - kubelet
       
   - name: reboot servers machines
     reboot:
