- hosts: servers
  become: yes
  vars:
    cpkgs:
      - runc
      - podman
      - catatonit
    ip_modules:
      - ip_vs
      - ip_vs_rr
      - ip_vs_wrr
      - ip_vs_sh
      - br_netfilter  

  tasks:

   - name: disable firewall service
     service:
        name: firewalld
        state: stopped
        enabled: false

   - name: Disable SWAP 
     shell: |
       swapoff -a

   - name: Disable SWAP in fstab 
     lineinfile:
       path: /etc/fstab
       regexp: 'swap'
       state: absent

   - name: uninstall docker conflicting packages on master and all nodes
     yum:
       name: '{{ cpkgs }}'
       state: absent
       update_cache: true

   - name: Configure docker-ce repository
     tags:
        - repos
     yum_repository:
      name: docker-ce
      description: docker-ce
      baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
      enabled: true
      gpgcheck: true
      repo_gpgcheck: true
      gpgkey:
        - https://download.docker.com/linux/centos/gpg
      state: present

   - name: install docker packages on master and all nodes
     shell: >
      yum install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin --allowerasing --nobest

   - name: start Docker service
     service:
       name: docker
       state: started
       enabled: true

   - name: disable SELinux
     command: setenforce 0
     ignore_errors: yes

   - name: disable SELinux on reboot
     selinux:
       state: disabled

   - name: configure network settings
     tags:
      - os-settings
     command: modprobe '{{ item }}'
     loop: '{{ ip_modules }}'

   - name: Modprobe
     tags:
      - os-settings
     lineinfile:
      path: "/etc/modules"
      line: "{{ item }}"
      create: yes
      state: present
     loop: "{{ ip_modules }}"

   - name:  set iptables
     tags:  
      - os-settings   
     sysctl:
      name: '{{ item }}'
      value: 1
      sysctl_set: yes
      state: present
      reload: yes
     loop:
      - net.bridge.bridge-nf-call-ip6tables
      - net.bridge.bridge-nf-call-iptables 

   - name: add Kubernetes YUM repository
     yum_repository:
      name: Kubernetes
      description: Kubernetes YUM repository
      enabled: true
      baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      gpgkey: 
        - https://packages.cloud.google.com/yum/doc/yum-key.gpg 
        - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      gpgcheck: true
      repo_gpgcheck: true
      state: present

   - name: install kubernetes packages
     yum:
      name: '{{ item }}'
      state: present
      update_cache: true
     loop:
      - kubeadm
      - kubelet
      - kubectl   

   - name: start kubelet
     service:
       name: kubelet
       enabled: yes
       state: started
       
   - name: reboot servers machines
     reboot:
