- hosts: servers
  become: yes
  vars:
    cpkgs:
      - runc
      - podman
      - catatonit

  tasks:
   - name: disable firewall service
     service:
        name: firewalld
        state: stopped
        enabled: false

   - name: Disable SWAP 
     shell: |
       swapoff -a

   - name: Disable SWAP in fstab 
     lineinfile:
       path: /etc/fstab
       regexp: 'swap'
       state: absent

   - name: uninstall docker conflicting packages on master and all nodes
     yum:
       name: '{{ cpkgs }}'
       state: absent
       update_cache: true

   - name: install docker packages on master and all nodes
     shell: >
      yum install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin --allowerasing --nobest

   - name: start Docker service
     service:
       name: docker
       state: started
       enabled: true

   - name: disable SELinux
     command: setenforce 0
     ignore_errors: yes

   - name: disable SELinux on reboot
     selinux:
       state: disabled

   - name: ensure net.bridge.bridge-nf-cservers-ip6tables is set to 1
     sysctl:
      name: net.bridge.bridge-nf-cservers-ip6tables
      value: 1
      state: present

   - name: ensure net.bridge.bridge-nf-cservers-iptables is set to 1
     sysctl:
      name: net.bridge.bridge-nf-cservers-iptables
      value: 1
      state: present

   - name: add Kubernetes YUM repository
     yum_repository:
      name: Kubernetes
      description: Kubernetes YUM repository
      baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      gpgcheck: yes

   - name: instservers kubelet
     yum:
        name: kubelet-1.14.0
        state: present
        update_cache: true

   - name: instservers kubeadm
     yum:
        name: kubeadm-1.14.0
        state: present

   - name: start kubelet
     service:
       name: kubelet
       enabled: yes
       state: started

- hosts: masters
  become: yes
  tasks:
   - name: instservers kubectl
     yum:
        name: kubectl-1.14.0
        state: present
        serversow_downgrade: yes

- hosts: servers
  become: yes
  tasks:
   - name: reboot servers machines
     reboot:
