- hosts: servers
  become: yes
  vars:
    cpkgs:
      - runc
      - podman
      - catatonit
    ip_modules:
      - ip_vs
      - ip_vs_rr
      - ip_vs_wrr
      - ip_vs_sh
      - br_netfilter  

  tasks:

   - name: disable firewall 
     service:
        name: firewalld
        state: stopped
        enabled: false

   - name: Disable SWAP 
     shell: |
       swapoff -a

   - name: Disable SWAP in fstab 
     lineinfile:
       path: /etc/fstab
       regexp: 'swap'
       state: absent

   - name: uninstall conflicting packages 
     yum:
       name: '{{ cpkgs }}'
       state: absent
       update_cache: true


   - name: install docker 
     shell: >
      yum install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin --allowerasing --nobest 
#     yum:
#      name: '{{ packages }}'
#      state: present
#      releasever: '18.09.9'
#      allow_downgrade: true 
#      update_cache: true
#     vars:
#      packages:
#        - docker-ce
#        - docker-ce-cli
#        - docker-compose-plugin


   - name: disable SELinux
     command: setenforce 0
     ignore_errors: yes

   - name: disable SELinux on reboot
     selinux:
       state: disabled

   - name: configure network settings
     tags:
      - os-settings
     command: modprobe '{{ item }}'
     loop: '{{ ip_modules }}'

   - name: Modprobe
     tags:
      - os-settings
     lineinfile:
      path: "/etc/modules"
      line: "{{ item }}"
      create: yes
      state: present
     loop: "{{ ip_modules }}"

   - name:  set iptables
     tags:  
      - os-settings   
     sysctl:
      name: '{{ item }}'
      value: 1
      sysctl_set: yes
      state: present
      reload: yes
     loop:
      - net.bridge.bridge-nf-call-ip6tables
      - net.bridge.bridge-nf-call-iptables 

   - name: configure kubernetes repo
     yum_repository:
      name: Kubernetes
      description: Kubernetes repo
      enabled: true
      baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      gpgkey: 
        - https://packages.cloud.google.com/yum/doc/yum-key.gpg 
        - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      gpgcheck: true
      repo_gpgcheck: true
      state: present

   - name: install packages
     yum:
      name: '{{ item }}'
      state: present
      update_cache: true
     loop:
      - kubeadm
      - kubelet
      - kubectl

   - name: start services
     service:
       name: '{{ item }}'
       enabled: yes
       state: started
     loop:
      - docker
      - kubelet
       
   - name: reboot servers machines
     reboot:
